-- ================================================================================
--   postgres SQL DDL Script File
-- ================================================================================


-- ===============================================================================
-- 
--   Generated by:      tedia2sql -- v1.2.12
--                      See http://tedia2sql.tigris.org/AUTHORS.html for tedia2sql author information
-- 
--   Target Database:   postgres
--   Generated at:      Mon Jun  4 20:33:26 2007
--   Input Files:       usersgroupsdir.dia cartsets.dia audio.dia scripts.dia showplans.dia sustainer.dia website.dia digiplay.dia
-- 
-- ================================================================================



-- Generated SQL Constraints Drop statements
-- --------------------------------------------------------------------



-- Generated Permissions Drops
-- --------------------------------------------------------------------



-- Special statements for postgres:pre databases
BEGIN transaction;


-- Generated SQL View Drop Statements
-- --------------------------------------------------------------------



-- Generated SQL Schema Drop statements
-- --------------------------------------------------------------------



-- Generated SQL Schema
-- --------------------------------------------------------------------


-- configs
create table configs (
  id                        serial not null,
  name                      character varying,
  description               character varying,
  constraint pk_Configs primary key (id)
) ;

-- dir
create table dir (
  id                        serial not null,
  parent                    integer,
  name                      character varying,
  notes                     character varying,
  constraint pk_Dir primary key (id)
) ;

-- dirgroups
create table dirgroups (
  id                        serial not null,
  dirid                     integer,
  groupid                   integer,
  permissions               bit(8),
  constraint pk_Dirgroups primary key (id)
) ;

-- dirusers
create table dirusers (
  id                        serial not null,
  dirid                     integer,
  userid                    integer,
  permissions               bit(8),
  constraint pk_Dirusers primary key (id)
) ;

-- usersgroups
create table usersgroups (
  id                        serial not null,
  groupid                   integer,
  userid                    integer,
  constraint pk_Usersgroups primary key (id)
) ;

-- groups
create table groups (
  id                        serial not null,
  name                      character varying,
  description               character varying,
  constraint pk_Groups primary key (id)
) ;

-- users
create table users (
  id                        serial not null,
  username                  character varying,
  password                  character(32),
  enabled                   character(1),
  constraint pk_Users primary key (id)
) ;

-- usersconfigs
create table usersconfigs (
  id                        serial not null,
  userid                    integer,
  configid                  integer,
  val                       character varying,
  constraint pk_Usersconfigs primary key (id)
) ;

-- cartproperties
create table cartproperties (
  id                        serial not null,
  name                      character varying not null,
  note                      character varying,
  constraint pk_Cartproperties primary key (id)
) ;

-- cartsaudio
create table cartsaudio (
  id                        serial not null,
  audioid                   integer not null,
  cartstyleid               integer not null,
  cart                      integer not null,
  cartwallid                integer not null,
  text                      character varying not null,
  constraint pk_Cartsaudio primary key (id)
) ;

-- cartsets
create table cartsets (
  id                        serial not null,
  name                      character varying not null,
  description               character varying,
  constraint pk_Cartsets primary key (id)
) ;

-- cartsetsdir
create table cartsetsdir (
  id                        serial not null,
  cartsetid                 integer not null,
  dirid                     integer not null,
  linktype                  smallint default 0 not null,
  constraint pk_Cartsetsdir primary key (id)
) ;

-- cartsetsgroups
create table cartsetsgroups (
  id                        serial not null,
  cartsetid                 integer not null,
  groupid                   integer not null,
  permissions               bit(8) not null,
  constraint pk_Cartsetsgroups primary key (id)
) ;

-- cartsetsusers
create table cartsetsusers (
  id                        serial not null,
  cartsetid                 integer not null,
  userid                    integer not null,
  permissions               bit(8) not null,
  constraint pk_Cartsetsusers primary key (id)
) ;

-- cartstyles
create table cartstyles (
  id                        serial not null,
  name                      character varying not null,
  description               character varying,
  constraint pk_Cartstyles primary key (id)
) ;

-- cartstyleprops
create table cartstyleprops (
  id                        serial not null,
  cartstyleid               integer not null,
  cartpropertyid            integer not null,
  value                     character varying not null,
  constraint pk_Cartstyleprops primary key (id)
) ;

-- cartwalls
create table cartwalls (
  id                        serial not null,
  name                      character varying not null,
  cartsetid                 integer not null,
  page                      integer not null,
  description               character varying,
  constraint pk_Cartwalls primary key (id)
) ;

-- advertschedule
create table advertschedule (
  id                        serial not null,
  audioid                   integer not null,
  start_date                date not null,
  end_date                  date not null,
  time_start                time without time zone,
  time_end                  time without time zone,
  frequency                 smallint not null,
  constraint pk_Advertschedule primary key (id)
) ;

-- albums
create table albums (
  id                        serial not null,
  name                      character varying not null,
  alt_name                  character varying,
  constraint pk_Albums primary key (id)
) ;

-- archives
create table archives (
  id                        serial not null,
  name                      character varying not null,
  localpath                 character varying not null,
  remotepath                character varying not null,
  constraint pk_Archives primary key (id)
) ;

-- artists
create table artists (
  id                        serial not null,
  name                      character varying not null,
  alt_name                  character varying,
  constraint pk_Artists primary key (id)
) ;

-- artistskeywords
create table artistskeywords (
  id                        serial not null,
  artistid                  integer not null,
  keywordid                 integer not null,
  constraint pk_Artistskeywords primary key (id)
) ;

-- audio
create table audio (
  id                        serial not null,
  md5                       character(32) not null,
  archive                   integer not null,
  length_smpl               integer not null,
  start_smpl                integer not null,
  end_smpl                  integer not null,
  intro_smpl                integer not null,
  extro_smpl                integer not null,
  type                      integer not null,
  creator                   integer not null,
  creation_date             integer not null,
  import_date               integer not null,
  title                     character varying not null,
  music_album               integer default 1 not null,
  music_track               smallint,
  music_released            smallint,
  advert_company            integer,
  advert_description        character varying,
  origin                    character varying,
  reclibid                  character varying,
  sustainer                 character(1),
  flagged                   character(1),
  censor                    character(1),
  notes                     character varying,
  param_vol                 smallint,
  param_speed               smallint,
  param_mood                smallint,
  param_endstyle            smallint,
  lifespan                  integer default 1 not null,
  rip_result                character varying,
  filetype                  character varying default 'raw'::character varying not null,
  constraint pk_Audio primary key (id)
) ;

-- audioartists
create table audioartists (
  id                        serial not null,
  audioid                   integer not null,
  artistid                  integer not null,
  constraint pk_Audioartists primary key (id)
) ;

-- audiocomments
create table audiocomments (
  id                        serial not null,
  audioid                   integer not null,
  userid                    integer not null,
  creationdate              integer not null,
  comment                   character varying,
  constraint pk_Audiocomments primary key (id)
) ;

-- audiodir
create table audiodir (
  id                        serial not null,
  audioid                   integer not null,
  dirid                     integer not null,
  linktype                  smallint default 0 not null,
  constraint pk_Audiodir primary key (id)
) ;

-- audiojinglepkgs
create table audiojinglepkgs (
  id                        serial not null,
  audioid                   integer not null,
  jinglepkgid               integer not null,
  jingletypeid              integer not null,
  constraint pk_Audiojinglepkgs primary key (id)
) ;

-- audiokeywords
create table audiokeywords (
  id                        serial not null,
  audioid                   integer not null,
  keywordid                 integer not null,
  constraint pk_Audiokeywords primary key (id)
) ;

-- audiolog
create table audiolog (
  id                        serial not null,
  audioid                   integer not null,
  userid                    integer not null,
  downloaddate              date not null,
  constraint pk_Audiolog primary key (id)
) ;

-- audioplaylists
create table audioplaylists (
  id                        serial not null,
  audioid                   integer not null,
  playlistid                integer not null,
  constraint pk_Audioplaylists primary key (id)
) ;

-- audiotypes
create table audiotypes (
  id                        serial not null,
  name                      character varying not null,
  description               character varying,
  constraint pk_Audiotypes primary key (id)
) ;

-- audiousers
create table audiousers (
  id                        serial not null,
  audioid                   integer not null,
  userid                    integer not null,
  permissions               bit(8) not null,
  constraint pk_Audiousers primary key (id)
) ;

-- companies
create table companies (
  id                        serial not null,
  name                      character varying not null,
  constraint pk_Companies primary key (id)
) ;

-- jinglepkgs
create table jinglepkgs (
  id                        serial not null,
  name                      character varying not null,
  description               character varying not null,
  enabled                   character(1) not null,
  constraint pk_Jinglepkgs primary key (id)
) ;

-- jingletypes
create table jingletypes (
  id                        serial not null,
  name                      character varying not null,
  description               character varying,
  constraint pk_Jingletypes primary key (id)
) ;

-- keywords
create table keywords (
  id                        serial not null,
  name                      character varying not null,
  name_similar              character varying,
  constraint pk_Keywords primary key (id)
) ;

-- lifespans
create table lifespans (
  id                        serial not null,
  name                      character varying not null,
  data                      integer not null,
  description               character varying,
  constraint pk_Lifespans primary key (id)
) ;

-- playlists
create table playlists (
  id                        serial not null,
  name                      character varying not null,
  constraint pk_Playlists primary key (id)
) ;

-- audiogroups
create table audiogroups (
  id                        serial not null,
  audioid                   integer not null,
  groupid                   integer not null,
  permissions               bit(8) not null,
  constraint pk_Audiogroups primary key (id)
) ;

-- scriptsgroups
create table scriptsgroups (
  id                        serial not null,
  scriptid                  integer not null,
  groupid                   integer not null,
  permissions               bit(8) not null,
  constraint pk_Scriptsgroups primary key (id)
) ;

-- scripts
create table scripts (
  id                        serial not null,
  name                      character varying not null,
  contents                  character varying,
  length                    integer,
  userid                    integer not null,
  creationdate              integer not null,
  constraint pk_Scripts primary key (id)
) ;

-- scriptsdir
create table scriptsdir (
  id                        serial not null,
  scriptid                  integer not null,
  dirid                     integer not null,
  linktype                  smallint default 0 not null,
  constraint pk_Scriptsdir primary key (id)
) ;

-- scriptsusers
create table scriptsusers (
  id                        serial not null,
  scriptid                  integer not null,
  userid                    integer not null,
  permissions               bit(8) not null,
  constraint pk_Scriptsusers primary key (id)
) ;

-- showitems
create table showitems (
  id                        serial not null,
  showplanid                integer not null,
  position                  smallint not null,
  title                     character varying not null,
  audioid                   integer,
  scriptid                  integer,
  comment                   character varying,
  length                    integer not null,
  constraint pk_Showitems primary key (id)
) ;

-- showplandir
create table showplandir (
  id                        serial not null,
  showplanid                integer not null,
  dirid                     integer not null,
  linktype                  smallint default 0 not null,
  constraint pk_Showplandir primary key (id)
) ;

-- showplangroups
create table showplangroups (
  id                        serial not null,
  showplanid                integer not null,
  groupid                   integer not null,
  permissions               bit(8) not null,
  constraint pk_Showplangroups primary key (id)
) ;

-- showplans
create table showplans (
  id                        serial not null,
  name                      character varying not null,
  userid                    integer not null,
  creationdate              integer not null,
  showdate                  integer,
  completed                 boolean not null,
  constraint pk_Showplans primary key (id)
) ;

-- showplanusers
create table showplanusers (
  id                        serial not null,
  showplanid                integer not null,
  userid                    integer not null,
  permissions               bit(8) not null,
  constraint pk_Showplanusers primary key (id)
) ;

-- bins
create table bins (
  id                        serial not null,
  name                      character varying not null,
  description               character varying,
  constraint pk_Bins primary key (id)
) ;

-- binsartists
create table binsartists (
  id                        serial not null,
  artistid                  integer not null,
  binid                     integer not null,
  constraint pk_Binsartists primary key (id)
) ;

-- binsaudio
create table binsaudio (
  id                        serial not null,
  audioid                   integer not null,
  binid                     integer not null,
  constraint pk_Binsaudio primary key (id)
) ;

-- binskeywords
create table binskeywords (
  id                        serial not null,
  keywordid                 integer not null,
  binid                     integer not null,
  constraint pk_Binskeywords primary key (id)
) ;

-- binsschedule
create table binsschedule (
  id                        serial not null,
  binid                     integer not null,
  bintype                   integer not null,
  day_start                 integer not null,
  hour_start                integer not null,
  length_hours              integer not null,
  binstart                  integer not null,
  binend                    integer not null,
  notes                     character varying,
  constraint pk_Binsschedule primary key (id)
) ;

-- extfeeds
create table extfeeds (
  id                        serial not null,
  name                      character varying not null,
  device                    character varying not null,
  constraint pk_Extfeeds primary key (id)
) ;

-- sustschedule
create table sustschedule (
  id                        serial not null,
  audioid                   integer,
  extfeedid                 integer,
  extfeed_length            integer,
  start                     integer not null,
  trim_start_smpl           integer not null,
  trim_end_smpl             integer not null,
  fade_in                   integer not null,
  fade_out                  integer not null,
  constraint pk_Sustschedule primary key (id)
) ;

-- cmscontent
create table cmscontent (
  contentid                 serial not null,
  regionid                  integer default 0 not null,
  timestamp                 integer default 0 not null,
  content                   bytea not null,
  userid                    integer default 0 not null,
  constraint pk_Cmscontent primary key (contentid)
) ;

-- cmsregions
create table cmsregions (
  regionid                  serial not null,
  name                      character varying(32) default ''::character varying not null,
  editrealm                 integer not null,
  viewrealm                 integer not null,
  inlinetoolbar             character varying(16) default 'Basic'::character varying not null,
  windowtoolbar             character varying(16) default 'Default'::character varying not null,
  constraint pk_Cmsregions primary key (regionid)
) ;

-- fieldvalidators
create table fieldvalidators (
  ruleid                    serial not null,
  vrclassname               character varying(45) default ''::character varying not null,
  description               text not null,
  modulename                character varying(16) default ''::character varying not null,
  constraint pk_Fieldvalidators primary key (ruleid)
) ;

-- formfields
create table formfields (
  fieldid                   serial not null,
  formname                  character varying(32) default ''::character varying not null,
  fieldname                 character varying(32) default ''::character varying not null,
  ruleid                    integer default 0 not null,
  modulename                character varying(16) default ''::character varying not null,
  constraint pk_Formfields primary key (fieldid)
) ;

-- forms
create table forms (
  formid                    serial not null,
  formname                  character varying(32) default ''::character varying not null,
  modelclass                character varying(32) default ''::character varying not null,
  modulename                character varying(32) default ''::character varying not null,
  realmid                   integer default 0 not null,
  validatorname             character varying(32),
  validatormodule           character varying(32),
  constraint pk_Forms primary key (formid)
) ;

-- logentries
create table logentries (
  entryid                   serial not null,
  message                   text not null,
  level                     character varying(16) default ''::character varying not null,
  module                    character varying(16),
  notes                     text,
  notify_date               timestamp(6) default now() not null,
  constraint pk_Logentries primary key (entryid)
) ;

-- realmgrouplink
create table realmgrouplink (
  groupid                   integer not null,
  realmid                   integer not null,
  allow                     character(1),
  constraint pk_Realmgrouplink primary key (groupid,realmid)
) ;

-- realms
create table realms (
  realmid                   serial not null,
  name                      character varying(32) default ''::character varying not null,
  parentid                  integer not null,
  description               character varying(128),
  depth                     smallint,
  realmpath                 character varying(255),
  constraint pk_Realms primary key (realmid)
) ;

-- realmuserlink
create table realmuserlink (
  userid                    serial not null,
  realmid                   integer not null,
  allow                     character(1),
  constraint pk_Realmuserlink primary key (userid,realmid)
) ;

-- sessions
create table sessions (
  sessionid                 serial not null,
  useragent                 character varying(128) default ''::character varying not null,
  ip                        character varying(15) default ''::character varying not null,
  rndidentifier             character varying(14) default ''::character varying not null,
  lastaccess                character varying(12) default ''::character varying not null,
  constraint pk_Sessions primary key (sessionid)
) ;

-- sessionvalues
create table sessionvalues (
  valueid                   serial not null,
  sessionid                 integer default 0 not null,
  skey                      character varying(32) default ''::character varying not null,
  svalue                    bytea not null,
  constraint pk_Sessionvalues primary key (valueid)
) ;

-- templates
create table templates (
  templateid                serial not null,
  filename                  character varying(32) default ''::character varying not null,
  viewerclassname           character varying(32) default ''::character varying not null,
  realmid                   integer default 0 not null,
  modulename                character varying(16) default ''::character varying not null,
  constraint pk_Templates primary key (templateid)
) ;

-- audioext
create table audioext (
  id                        serial not null,
  library_id                character varying not null,
  title                     character varying not null,
  artist_name               character varying not null,
  album_name                character varying,
  constraint pk_Audioext primary key (id)
) ;

-- changelog
create table changelog (
  id                        serial not null,
  datetime                  integer not null,
  userid                    integer not null,
  relation                  character varying not null,
  record                    integer not null,
  field                     character varying not null,
  oldvalue                  character varying not null,
  comment                   character varying,
  constraint pk_Changelog primary key (id)
) ;

-- configuration
create table configuration (
  id                        serial not null,
  parameter                 character varying not null,
  val                       character varying not null,
  location                  integer not null,
  constraint pk_Configuration primary key (id)
) ;

-- email
create table email (
  id                        serial not null,
  new_flag                  character(1) not null,
  datetime                  integer not null,
  sender                    character varying not null,
  subject                   character varying,
  body                      character varying,
  constraint pk_Email primary key (id)
) ;

-- log
create table log (
  id                        serial not null,
  location                  integer not null,
  userid                    integer not null,
  datetime                  integer not null,
  track_title               character varying not null,
  track_artist              character varying not null,
  constraint pk_Log primary key (id)
) ;

-- requests
create table requests (
  id                        serial not null,
  name                      character varying,
  artistname                character varying,
  date                      integer not null,
  userid                    integer not null,
  constraint pk_Requests primary key (id)
) ;

-- tasks
create table tasks (
  id                        serial not null,
  name                      character varying not null,
  description               character varying not null,
  sql_query                 character varying,
  process                   character varying,
  parameters                character varying,
  constraint pk_Tasks primary key (id)
) ;

-- taskschedule
create table taskschedule (
  id                        serial not null,
  taskid                    integer not null,
  dayofweek                 smallint not null,
  timeofday                 integer not null,
  constraint pk_Taskschedule primary key (id)
) ;

-- patches
create table patches (
  id                        serial not null,
  branch                    character varying,
  version                   integer,
  constraint pk_Patches primary key (id)
) ;














































































-- Generated SQL Views
-- --------------------------------------------------------------------



-- Special statements for postgres:post databases
\i digiplay-views.sql
END transaction;


-- Generated Permissions
-- --------------------------------------------------------------------



-- Generated SQL Insert statements
-- --------------------------------------------------------------------



-- Generated SQL Constraints
-- --------------------------------------------------------------------

create unique index idx_cartsetsdir_uniquelink on cartsetsdir  (cartsetid,linktype) ;
create unique index idx_artists_name on artists using btree (name) ;
create index idx_artists_alt_name on artists using btree (alt_name) ;
create unique index idx_audio_md5 on audio using btree (md5) ;
create index idx_audio_title on audio using btree (title) ;
create index idx_audiodir_audio on audiodir using btree (audioid) ;
create index idx_audiodir_dirid on audiodir using btree (dirid) ;
create unique index idx_audiodir_uniquelink on audiodir  (audioid,linktype) ;
create unique index idx_scriptsdir_uniquelink on scriptsdir  (scriptid,linktype) ;
create unique index idx_showplans_uniquelink on showplandir  (showplanid,linktype) ;
alter table usersgroups add constraint fk_usersgroups_userid
  foreign key (userid)
  references users (id)  ;
alter table usersgroups add constraint fk_usersgroups_groupid
  foreign key (groupid)
  references groups (id)  ;
alter table dirusers add constraint dirusers_fk_Dirid
  foreign key (dirId)
  references dir (id)  ;
alter table dirusers add constraint fk_dirusers_userid
  foreign key (userid)
  references users (id)  ;
alter table dirgroups add constraint fk_dirgroups_dirid
  foreign key (dirid)
  references dir (id)  ;
alter table dirgroups add constraint fk_dirgroups_groupid
  foreign key (groupid)
  references groups (id)  ;
alter table usersconfigs add constraint fk_userconfigs_userid
  foreign key (userid)
  references users (id)  ;
alter table usersconfigs add constraint fk_userconfigs_configid
  foreign key (configid)
  references configs (id)  ;
alter table cartsetsdir add constraint fk_cartsetsdir_cartsetid
  foreign key (cartsetid)
  references cartsets (id)  ;
alter table cartsetsgroups add constraint fk_cartsetgroups_cartsetid
  foreign key (cartsetid)
  references cartsets (id)  ;
alter table cartwalls add constraint fk_cartwalls_cartsetid
  foreign key (cartsetid)
  references cartsets (id)  ;
alter table cartsetsusers add constraint fk_cartsetsusers_cartsetid
  foreign key (cartsetid)
  references cartsets (id)  ;
alter table cartsaudio add constraint fk_cartsaudio_cartwallid
  foreign key (cartwallid)
  references cartwalls (id)  ;
alter table cartsaudio add constraint fk_cartsaudio_cartstyleid
  foreign key (cartstyleid)
  references cartstyles (id)  ;
alter table cartstyleprops add constraint fk_cartstyleprops_cartstyleid
  foreign key (cartstyleid)
  references cartstyles (id)  ;
alter table cartstyleprops add constraint fk_cartstyleprops_cartpropertyid
  foreign key (cartpropertyid)
  references cartproperties (id)  ;
alter table cartsetsdir add constraint fk_cartsetsdir_dirid
  foreign key (dirid)
  references dir (id)  ;
alter table cartsetsusers add constraint fk_cartsetsusers_userid
  foreign key (userid)
  references users (id)  ;
alter table cartsetsgroups add constraint fk_cartsetsgroups_groupid
  foreign key (groupid)
  references groups (id)  ;
alter table cartsaudio add constraint fk_cartsaudio_audioid
  foreign key (audioid)
  references audio (id)  ;
alter table audiogroups add constraint fk_audiogroups_audioid
  foreign key (audioid)
  references audio (id)  ;
alter table audioplaylists add constraint fk_audioplaylists_audioid
  foreign key (audioid)
  references audio (id)  ;
alter table audiolog add constraint fk_audiolog_audioid
  foreign key (audioid)
  references audio (id)  ;
alter table audiousers add constraint fk_audiousers_audioid
  foreign key (audioid)
  references audio (id)  ;
alter table audiocomments add constraint fk_audiocomments_audioid
  foreign key (audioid)
  references audio (id)  ;
alter table audio add constraint fk_audio_advert_company
  foreign key (advert_company)
  references companies (id)  ;
alter table audioartists add constraint fk_audioartists_audioid
  foreign key (audioid)
  references audio (id)  ;
alter table audio add constraint fk_audio_music_album
  foreign key (music_album)
  references albums (id)  ;
alter table audiokeywords add constraint fk_audiokeywords_audioid
  foreign key (audioid)
  references audio (id)  ;
alter table audiojinglepkgs add constraint fk_audiojinglepkgs_audioid
  foreign key (audioid)
  references audio (id)  ;
alter table audio add constraint fk_audio_lifespan
  foreign key (lifespan)
  references lifespans (id)  ;
alter table audio add constraint fk_audio_archive
  foreign key (archive)
  references archives (id)  ;
alter table audiodir add constraint fk_audiodir_audioid
  foreign key (audioid)
  references audio (id)  ;
alter table audioplaylists add constraint fk_audioplaylists_playlistid
  foreign key (playlistid)
  references playlists (id)  ;
alter table audio add constraint fk_audio_type
  foreign key (type)
  references audiotypes (id)  ;
alter table audiojinglepkgs add constraint fk_audiojinglepkgs_jinglepkgid
  foreign key (jinglepkgid)
  references jinglepkgs (id)  ;
alter table audiojinglepkgs add constraint fk_audiojinglepkgs_jingletypeid
  foreign key (jingletypeid)
  references jingletypes (id)  ;
alter table audiokeywords add constraint fk_audiokeywords_keywordid
  foreign key (keywordid)
  references keywords (id)  ;
alter table audioartists add constraint fk_audioartists_artistid
  foreign key (artistid)
  references artists (id)  ;
alter table artistskeywords add constraint fk_artistskeywords_artistid
  foreign key (artistid)
  references artists (id)  ;
alter table artistskeywords add constraint fk_artistskeywords_keywordid
  foreign key (keywordid)
  references keywords (id)  ;
alter table advertschedule add constraint fk_advertschedule_audioid
  foreign key (audioid)
  references audio (id)  ;
alter table audiogroups add constraint fk_audiogroups_groupid
  foreign key (groupid)
  references groups (id)  ;
alter table audiodir add constraint fk_audiodir_dirid
  foreign key (dirid)
  references dir (id)  ;
alter table audio add constraint fk_audio_creator
  foreign key (creator)
  references users (id)  ;
alter table audiolog add constraint fk_audiolog_userid
  foreign key (userid)
  references users (id)  ;
alter table audiousers add constraint fk_audiousers_userid
  foreign key (userid)
  references users (id)  ;
alter table audiocomments add constraint fk_audiocomments_userid
  foreign key (userid)
  references users (id)  ;
alter table scriptsusers add constraint fk_scriptsusers_scriptid
  foreign key (scriptid)
  references scripts (id)  ;
alter table scriptsdir add constraint fk_scriptsdir_scriptid
  foreign key (scriptid)
  references scripts (id)  ;
alter table scriptsgroups add constraint fk_scriptsgroups_scriptid
  foreign key (scriptid)
  references scripts (id)  ;
alter table scriptsusers add constraint fk_scriptsusers_userid
  foreign key (userid)
  references users (id)  ;
alter table scriptsdir add constraint fk_scriptsdir_dirid
  foreign key (dirid)
  references dir (id)  ;
alter table scriptsgroups add constraint fk_scriptsgroups_groupid
  foreign key (groupid)
  references groups (id)  ;
alter table scripts add constraint fk_scripts_userid
  foreign key (userid)
  references users (id)  ;
alter table showplandir add constraint fk_showplandir_showplanid
  foreign key (showplanid)
  references showplans (id)  ;
alter table showplanusers add constraint fk_showplanusers_showplanid
  foreign key (showplanid)
  references showplans (id)  ;
alter table showplangroups add constraint fk_showplangroups_showplanid
  foreign key (showplanid)
  references showplans (id)  ;
alter table showitems add constraint fk_showitems_showplanid
  foreign key (showplanid)
  references showplans (id)  ;
alter table showitems add constraint fk_showplanitems_audioid
  foreign key (audioid)
  references audio (id)  ;
alter table showitems add constraint fk_showitems_scriptid
  foreign key (scriptid)
  references scripts (id)  ;
alter table showplandir add constraint fk_showplandir
  foreign key (dirid)
  references dir (id)  ;
alter table showplanusers add constraint fk_showplanusers_userid
  foreign key (userid)
  references users (id)  ;
alter table showplangroups add constraint fk_showplangroups_groupid
  foreign key (groupid)
  references groups (id)  ;
alter table binsaudio add constraint fk_binsaudio_binid
  foreign key (binid)
  references bins (id)  ;
alter table binsartists add constraint fk_binsartists_binid
  foreign key (binid)
  references bins (id)  ;
alter table binskeywords add constraint fk_binskeywords_binid
  foreign key (binid)
  references bins (id)  ;
alter table binsschedule add constraint fk_binsschedule_binid
  foreign key (binid)
  references bins (id)  ;
alter table sustschedule add constraint fk_sustschedule_extfeedid
  foreign key (extfeedid)
  references extfeeds (id)  ;
alter table binsaudio add constraint fk_binsaudio_audioid
  foreign key (audioid)
  references audio (id)  ;
alter table binsartists add constraint fk_binsartists_artistid
  foreign key (artistid)
  references artists (id)  ;
alter table binskeywords add constraint fk_binskeywords_keywordid
  foreign key (keywordid)
  references keywords (id)  ;
alter table realmuserlink add constraint fk_realmuserlink_realmid
  foreign key (realmid)
  references realms (realmid)  ;
alter table realmgrouplink add constraint fk_realmgrouplink_realmid
  foreign key (realmid)
  references realms (realmid)  ;
alter table realmuserlink add constraint fk_realuserlink_userid
  foreign key (userid)
  references users (id)  ;
alter table realmgrouplink add constraint fk_realmgrouplink_groupid
  foreign key (groupid)
  references groups (id)  ;
alter table templates add constraint fk_templates_realmid
  foreign key (realmid)
  references realms (realmid)  ;
alter table forms add constraint fk_forms_realmid
  foreign key (realmid)
  references realms (realmid)  ;
alter table cmsregions add constraint fk_cmsregions_editrealm
  foreign key (editrealm)
  references realms (realmid)  ;
alter table cmscontent add constraint fk_cmscontent_regionid
  foreign key (regionid)
  references cmsregions (regionid)  ;
alter table cmscontent add constraint fk_cmscontent_userid
  foreign key (userid)
  references users (id)  ;
alter table formfields add constraint fk_formfields_ruleid
  foreign key (ruleid)
  references fieldvalidators (ruleid)  ;
alter table sessionvalues add constraint fk_sessionvalues_sessionid
  foreign key (sessionid)
  references sessions (sessionid)  ;
alter table cmsregions add constraint fk_cmsregions_viewrealm
  foreign key (viewrealm)
  references realms (realmid)  ;
alter table taskschedule add constraint fk_taskschedule_taskid
  foreign key (taskid)
  references tasks (id)  ;
alter table log add constraint fk_log_userid
  foreign key (userid)
  references users (id)  ;
alter table requests add constraint fk_requests_userid
  foreign key (userid)
  references users (id)  ;
alter table changelog add constraint fk_changelog_userid
  foreign key (userid)
  references users (id)  ;

