
-- DO NOT EDIT THIS FILE, IT IS AUTOGENERATED!! --
--    This SQL DDL script was generated by Microsoft Visual Studio (Release Date: LOCAL BUILD).

--    Driver Used : Microsoft Visual Studio - IBM DB2 Universal Database Driver.
--    Document    : G:\Data\cc\raw\digiplay\Database Design v2 (VISIO 2002).vsd.
--    Time Created: 09 April 2006 15:53.
--    Operation   : From Visio Generate Wizard.
--    Connected data source : No connection.
--    Connected server      : No connection.
--    Connected database    : Not applicable.




create database digiplay;
create user digiplay_user;
\c digiplay
begin transaction;

create table "changelog" ( 
	"id" SERIAL,
	"time" INTEGER not null,
	"user" INTEGER not null,
	"table" VARCHAR not null,
	"table_id" INTEGER not null, constraint "changelog_PK" primary key ("id") ); 

create table "audioext" ( 
	"id" SERIAL,
	"library_id" VARCHAR not null,
	"title" VARCHAR not null,
	"artist_name" VARCHAR not null,
	"album_name" VARCHAR, constraint "audioext_PK" primary key ("id") ); 

create table "playlist" ( 
	"id" SERIAL,
	"audio" INTEGER not null,
	"playlist" VARCHAR not null, constraint "playlist_PK" primary key ("id") ); 

create table "cartstyleprops" ( 
	"id" SERIAL,
	"style" INTEGER not null,
	"property" INTEGER not null,
	"value" VARCHAR not null, constraint "cartstyleprops_PK" primary key ("id") ); 

create table "binsaudio" ( 
	"id" SERIAL,
	"audio" INTEGER not null,
	"sustbin" INTEGER not null, constraint "binsaudio_PK" primary key ("id") ); 

create table "bins" ( 
	"id" SERIAL,
	"name" VARCHAR not null,
	"description" VARCHAR, constraint "bins_PK" primary key ("id") ); 

create table "audiojinglepkgs" ( 
	"id" SERIAL,
	"audio" INTEGER not null,
	"jinglepkg" INTEGER not null,
	"jingletype" INTEGER not null, constraint "audiojinglepkgs_PK" primary key ("id") ); 

create table "groupaccess" ( 
	"id" SERIAL,
	"groupid" INTEGER not null,
	"privilage" INTEGER not null, constraint "groupaccess_PK" primary key ("id") ); 

create table "audiodir" ( 
	"id" SERIAL,
	"audio" INTEGER not null,
	"directory" INTEGER not null, constraint "audiodir_PK" primary key ("id") ); 

create table "audioartists" ( 
	"id" SERIAL,
	"audio" INTEGER not null,
	"artist" INTEGER not null, constraint "audioartists_PK" primary key ("id") ); 

create table "cartstyle" ( 
	"id" SERIAL,
	"name" VARCHAR not null,
	"description" VARCHAR, constraint "cartstyle_PK" primary key ("id") ); 

create table "lifespans" ( 
	"id" SERIAL,
	"name" VARCHAR not null,
	"data" INTEGER,
	"description" VARCHAR, constraint "lifespans_PK" primary key ("id") ); 

create table "cartproperties" ( 
	"id" SERIAL,
	"name" VARCHAR not null,
	"note" VARCHAR, constraint "cartproperties_PK" primary key ("id") ); 

create table "binsschedule" ( 
	"id" SERIAL,
	"sustbin" INTEGER not null,
	"type" INTEGER not null,
	"day_start" INTEGER not null,
	"hour_start" INTEGER not null,
	"length_hours" INTEGER not null,
	"start" INTEGER not null,
	"end" INTEGER not null,
	"notes" VARCHAR, constraint "binsschedule_PK" primary key ("id") ); 

create table "binsartists" ( 
	"id" SERIAL,
	"artist" INTEGER not null,
	"sustbin" INTEGER not null, constraint "binsartists_PK" primary key ("id") ); 

create table "binskeywords" ( 
	"id" SERIAL,
	"keyword" INTEGER not null,
	"sustbin" INTEGER not null, constraint "binskeywords_PK" primary key ("id") ); 

create table "audiolog" ( 
	"id" SERIAL,
	"audio" INTEGER not null,
	"userid" INTEGER not null,
	"download_date" DATE not null,
	"download_time" TIME not null, constraint "audiolog_PK" primary key ("id") ); 

create table "usercuetypes" ( 
	"id" SERIAL,
	"name" VARCHAR not null,
	"description" VARCHAR, constraint "usercuetypes_PK" primary key ("id") ); 

create table "sustshows" ( 
	"id" SERIAL,
	"show" INTEGER not null,
	"start" INTEGER not null,
	"length" INTEGER not null, constraint "sustshows_PK" primary key ("id") ); 

create table "cartsets" ( 
	"id" SERIAL,
	"name" VARCHAR not null,
	"userid" INTEGER not null,
	"directory" INTEGER not null,
	"description" VARCHAR, constraint "cartsets_PK" primary key ("id") ); 

create table "jingletypes" ( 
	"id" SERIAL,
	"name" VARCHAR not null,
	"description" VARCHAR, constraint "jingletypes_PK" primary key ("id") ); 

create table "usercues" ( 
	"id" SERIAL,
	"usershowaudio" INTEGER not null,
	"type" INTEGER not null,
	"cue_smpl" INTEGER not null,
	"data" INTEGER,
	"note" VARCHAR, constraint "usercues_PK" primary key ("id") ); 

create table "usershownotes" ( 
	"id" SERIAL,
	"usershow" INTEGER not null,
	"playlist_position" SMALLINT not null,
	"note" VARCHAR,
	"length" INTEGER, constraint "usershownotes_PK" primary key ("id") ); 

create table "usershowsaudio" ( 
	"id" SERIAL,
	"usershow" INTEGER not null,
	"audio" INTEGER not null,
	"playlist_position" SMALLINT not null,
	"note" VARCHAR,
	"cue_up" INTEGER, constraint "usershowsaudio_PK" primary key ("id") ); 

create table "usershows" ( 
	"id" SERIAL,
	"name" VARCHAR not null,
	"userid" INTEGER not null,
	"directory" INTEGER not null,
	"start" INTEGER,
	"length" INTEGER, constraint "usershows_PK" primary key ("id") ); 

create table "cartsaudio" ( 
	"id" SERIAL,
	"audio" INTEGER not null,
	"style" INTEGER not null,
	"cart" INTEGER not null,
	"cartwall" INTEGER not null,
	"text" VARCHAR not null, constraint "cartsaudio_PK" primary key ("id") ); 

create table "audiotypes" ( 
	"id" SERIAL,
	"name" VARCHAR not null,
	"description" VARCHAR, constraint "audiotypes_PK" primary key ("id") ); 

create table "cartwalls" ( 
	"id" SERIAL,
	"name" VARCHAR not null,
	"cartset" INTEGER not null,
	"page" INTEGER not null,
	"description" VARCHAR, constraint "cartwalls_PK" primary key ("id") ); 

create table "artistskeywords" ( 
	"id" SERIAL,
	"artist" INTEGER not null,
	"keyword" INTEGER not null, constraint "artistskeywords_PK" primary key ("id") ); 

create table "tasks" ( 
	"id" SERIAL,
	"name" VARCHAR not null,
	"description" VARCHAR not null,
	"sql_query" VARCHAR,
	"process" VARCHAR,
	"parameters" VARCHAR, constraint "tasks_PK" primary key ("id") ); 

create table "archives" ( 
	"id" SERIAL,
	"name" VARCHAR not null,
	"localpath" VARCHAR not null,
	"remotepath" VARCHAR not null, constraint "archives_PK" primary key ("id") ); 

create table "companies" ( 
	"id" SERIAL,
	"name" VARCHAR not null, constraint "companies_PK" primary key ("id") ); 

create table "jinglepkgs" ( 
	"id" SERIAL,
	"name" VARCHAR not null,
	"description" VARCHAR not null,
	"enabled" CHARACTER(1) not null, constraint "jinglepkgs_PK" primary key ("id") ); 

create table "audiogroups" ( 
	"id" SERIAL,
	"audio" INTEGER not null,
	"groupid" INTEGER not null,
	"permissions" CHARACTER(2), constraint "audiogroups_PK" primary key ("id") ); 

create table "audiousers" ( 
	"id" SERIAL,
	"audio" INTEGER not null,
	"userid" INTEGER not null,
	"permissions" CHARACTER(2), constraint "audiousers_PK" primary key ("id") ); 

create table "audio" ( 
	"id" SERIAL,
	"md5" CHARACTER(32) not null,
	"archive" INTEGER not null,
	"length_smpl" INTEGER not null,
	"start_smpl" INTEGER not null,
	"end_smpl" INTEGER not null,
	"intro_smpl" INTEGER not null,
	"extro_smpl" INTEGER not null,
	"type" INTEGER not null,
	"creator" INTEGER not null,
	"creation_date" INTEGER not null,
	"import_date" INTEGER not null,
	"title" VARCHAR not null,
	"music_album" INTEGER,
	"music_track" SMALLINT,
	"music_released" SMALLINT,
	"advert_company" INTEGER,
	"advert_description" VARCHAR,
	"origin" VARCHAR,
	"reclibid" VARCHAR,
	"sustainer" CHARACTER(1),
	"flagged" CHARACTER(1),
	"censor" CHARACTER(1) not null,
	"notes" VARCHAR,
	"param_vol" SMALLINT,
	"param_speed" SMALLINT,
	"param_mood" SMALLINT,
	"param_endstyle" SMALLINT,
	"lifespan" INTEGER not null,
	"rip_result" VARCHAR, constraint "audio_PK" primary key ("id") ); 

create table "dirusers" ( 
	"id" SERIAL,
	"directory" INTEGER not null,
	"userid" INTEGER not null,
	"permissions" CHARACTER(2), constraint "dirusers_PK" primary key ("id") ); 

create table "dirgroups" ( 
	"id" SERIAL,
	"directory" INTEGER not null,
	"groupid" INTEGER not null,
	"permissions" CHARACTER(2), constraint "dirgroups_PK" primary key ("id") ); 

create table "groupmembers" ( 
	"id" SERIAL,
	"groupid" INTEGER not null,
	"userid" INTEGER not null, constraint "groupmembers_PK" primary key ("id") ); 

create table "groups" ( 
	"id" SERIAL,
	"name" VARCHAR not null,
	"description" VARCHAR not null, constraint "groups_PK" primary key ("id") ); 

create table "dir" ( 
	"id" SERIAL,
	"parent" INTEGER not null,
	"name" VARCHAR not null,
	"notes" VARCHAR, constraint "dir_PK" primary key ("id") ); 

create table "usersconfigs" ( 
	"id" SERIAL,
	"userid" INTEGER not null,
	"configoption" INTEGER not null,
	"val" VARCHAR not null, constraint "usersconfigs_PK" primary key ("id") ); 

create table "configs" ( 
	"id" SERIAL,
	"name" VARCHAR not null,
	"description" VARCHAR, constraint "configs_PK" primary key ("id") ); 

create table "email" ( 
	"id" SERIAL,
	"new_flag" CHARACTER(1) not null,
	"datetime" INTEGER not null,
	"sender" VARCHAR not null,
	"subject" VARCHAR,
	"body" VARCHAR, constraint "email_PK" primary key ("id") ); 

create table "useraccess" ( 
	"id" SERIAL,
	"userid" INTEGER not null,
	"privilage" INTEGER not null, constraint "useraccess_PK" primary key ("id") ); 

create table "privilages" ( 
	"id" SERIAL,
	"name" VARCHAR not null,
	"description" VARCHAR, constraint "privilages_PK" primary key ("id") ); 

create table "users" ( 
	"id" SERIAL,
	"username" VARCHAR not null,
	"password" CHARACTER(32),
	"enabled" CHARACTER(1) not null, constraint "users_PK" primary key ("id") ); 

create table "taskschedule" ( 
	"id" SERIAL,
	"task" INTEGER not null,
	"dayofweek" SMALLINT not null,
	"timeofday" INTEGER not null, constraint "taskschedule_PK" primary key ("id") ); 

create table "configuration" ( 
	"id" SERIAL,
	"parameter" VARCHAR not null,
	"val" VARCHAR not null,
	"location" INTEGER not null, constraint "configuration_PK" primary key ("id") ); 

create table "sustschedule" ( 
	"id" SERIAL,
	"audio" INTEGER,
	"extfeed" INTEGER,
	"extfeed_length" INTEGER,
	"start" INTEGER not null,
	"trim_start_smpl" INTEGER not null,
	"trim_end_smpl" INTEGER not null,
	"fade_in" INTEGER not null,
	"fade_out" INTEGER not null, constraint "sustschedule_PK" primary key ("id") ); 

create table "advertschedule" ( 
	"id" SERIAL,
	"advert" INTEGER not null,
	"start_date" DATE not null,
	"end_date" DATE not null,
	"time_start" TIME,
	"time_end" TIME,
	"frequency" SMALLINT not null, constraint "advertschedule_PK" primary key ("id") ); 

create table "extfeeds" ( 
	"id" SERIAL,
	"name" VARCHAR not null,
	"device" VARCHAR not null, constraint "extfeeds_PK" primary key ("id") ); 

create table "log" ( 
	"id" SERIAL,
	"location" INTEGER not null,
	"userid" INTEGER not null,
	"datetime" INTEGER not null,
	"track_title" VARCHAR not null,
	"track_artist" VARCHAR not null, constraint "log_PK" primary key ("id") ); 

create table "audiokeywords" ( 
	"id" SERIAL,
	"track" INTEGER not null,
	"keyword" INTEGER not null, constraint "audiokeywords_PK" primary key ("id") ); 

create table "keywords" ( 
	"id" SERIAL,
	"name" VARCHAR not null,
	"similar" VARCHAR, constraint "keywords_PK" primary key ("id") ); 

create table "albums" ( 
	"id" SERIAL,
	"name" VARCHAR not null,
	"alt_name" VARCHAR, constraint "albums_PK" primary key ("id") ); 

create table "artists" ( 
	"id" SERIAL,
	"name" VARCHAR not null,
	"alt_name" VARCHAR, constraint "artists_PK" primary key ("id") ); 

alter table "changelog"
	add constraint "users_FK11" foreign key (
		"id")
	 references "users" (
		"id") on update restrict on delete restrict; 

alter table "playlist"
	add constraint "audio_FK13" foreign key (
		"audio")
	 references "audio" (
		"id") on update restrict on delete restrict; 

alter table "cartstyleprops"
	add constraint "cartstyle_FK2" foreign key (
		"style")
	 references "cartstyle" (
		"id") on update restrict on delete restrict; 

alter table "cartstyleprops"
	add constraint "cartproperties_FK1" foreign key (
		"property")
	 references "cartproperties" (
		"id") on update restrict on delete restrict; 

alter table "binsaudio"
	add constraint "audio_FK12" foreign key (
		"audio")
	 references "audio" (
		"id") on update restrict on delete restrict; 

alter table "binsaudio"
	add constraint "bins_FK1" foreign key (
		"sustbin")
	 references "bins" (
		"id") on update restrict on delete restrict; 

alter table "audiojinglepkgs"
	add constraint "audio_FK11" foreign key (
		"audio")
	 references "audio" (
		"id") on update restrict on delete restrict; 

alter table "audiojinglepkgs"
	add constraint "jinglepkgs_FK1" foreign key (
		"jinglepkg")
	 references "jinglepkgs" (
		"id") on update restrict on delete restrict; 

alter table "audiojinglepkgs"
	add constraint "jingletypes_FK1" foreign key (
		"jingletype")
	 references "jingletypes" (
		"id") on update restrict on delete restrict; 

alter table "groupaccess"
	add constraint "groups_FK4" foreign key (
		"groupid")
	 references "groups" (
		"id") on update restrict on delete restrict; 

alter table "groupaccess"
	add constraint "privilages_FK2" foreign key (
		"privilage")
	 references "privilages" (
		"id") on update restrict on delete restrict; 

alter table "audiodir"
	add constraint "audio_FK10" foreign key (
		"audio")
	 references "audio" (
		"id") on update restrict on delete restrict; 

alter table "audiodir"
	add constraint "dir_FK5" foreign key (
		"directory")
	 references "dir" (
		"id") on update restrict on delete restrict; 

alter table "audioartists"
	add constraint "audio_FK9" foreign key (
		"audio")
	 references "audio" (
		"id") on update restrict on delete restrict; 

alter table "audioartists"
	add constraint "artists_FK3" foreign key (
		"artist")
	 references "artists" (
		"id") on update restrict on delete restrict; 

alter table "binsschedule"
	add constraint "bins_FK4" foreign key (
		"sustbin")
	 references "bins" (
		"id") on update restrict on delete restrict; 

alter table "binsartists"
	add constraint "bins_FK2" foreign key (
		"sustbin")
	 references "bins" (
		"id") on update restrict on delete restrict; 

alter table "binsartists"
	add constraint "artists_FK2" foreign key (
		"artist")
	 references "artists" (
		"id") on update restrict on delete restrict; 

alter table "binskeywords"
	add constraint "bins_FK3" foreign key (
		"sustbin")
	 references "bins" (
		"id") on update restrict on delete restrict; 

alter table "binskeywords"
	add constraint "keywords_FK3" foreign key (
		"keyword")
	 references "keywords" (
		"id") on update restrict on delete restrict; 

alter table "audiolog"
	add constraint "audio_FK8" foreign key (
		"audio")
	 references "audio" (
		"id") on update restrict on delete restrict; 

alter table "audiolog"
	add constraint "users_FK7" foreign key (
		"userid")
	 references "users" (
		"id") on update restrict on delete restrict; 

alter table "sustshows"
	add constraint "usershows_FK3" foreign key (
		"show")
	 references "usershows" (
		"id") on update restrict on delete restrict; 

alter table "cartsets"
	add constraint "dir_FK3" foreign key (
		"directory")
	 references "dir" (
		"id") on update restrict on delete restrict; 

alter table "cartsets"
	add constraint "users_FK10" foreign key (
		"userid")
	 references "users" (
		"id") on update restrict on delete restrict; 

alter table "usercues"
	add constraint "usershowsaudio_FK1" foreign key (
		"usershowaudio")
	 references "usershowsaudio" (
		"id") on update restrict on delete restrict; 

alter table "usercues"
	add constraint "usercuetypes_FK1" foreign key (
		"type")
	 references "usercuetypes" (
		"id") on update restrict on delete restrict; 

alter table "usershownotes"
	add constraint "usershows_FK2" foreign key (
		"usershow")
	 references "usershows" (
		"id") on update restrict on delete restrict; 

alter table "usershowsaudio"
	add constraint "usershows_FK1" foreign key (
		"usershow")
	 references "usershows" (
		"id") on update restrict on delete restrict; 

alter table "usershowsaudio"
	add constraint "audio_FK7" foreign key (
		"audio")
	 references "audio" (
		"id") on update restrict on delete restrict; 

alter table "usershowsaudio"
	add constraint "usercues_FK1" foreign key (
		"cue_up")
	 references "usercues" (
		"id") on update restrict on delete restrict; 

alter table "usershows"
	add constraint "dir_FK4" foreign key (
		"directory")
	 references "dir" (
		"id") on update restrict on delete restrict; 

alter table "usershows"
	add constraint "users_FK8" foreign key (
		"userid")
	 references "users" (
		"id") on update restrict on delete restrict; 

alter table "cartsaudio"
	add constraint "audio_FK6" foreign key (
		"audio")
	 references "audio" (
		"id") on update restrict on delete restrict; 

alter table "cartsaudio"
	add constraint "cartstyle_FK1" foreign key (
		"style")
	 references "cartstyle" (
		"id") on update restrict on delete restrict; 

alter table "cartsaudio"
	add constraint "cartwalls_FK1" foreign key (
		"cartwall")
	 references "cartwalls" (
		"id") on update restrict on delete restrict; 

alter table "cartwalls"
	add constraint "cartsets_FK1" foreign key (
		"cartset")
	 references "cartsets" (
		"id") on update restrict on delete restrict; 

alter table "artistskeywords"
	add constraint "artists_FK1" foreign key (
		"artist")
	 references "artists" (
		"id") on update restrict on delete restrict; 

alter table "artistskeywords"
	add constraint "keywords_FK1" foreign key (
		"keyword")
	 references "keywords" (
		"id") on update restrict on delete restrict; 

alter table "audiogroups"
	add constraint "groups_FK3" foreign key (
		"groupid")
	 references "groups" (
		"id") on update restrict on delete restrict; 

alter table "audiogroups"
	add constraint "audio_FK5" foreign key (
		"audio")
	 references "audio" (
		"id") on update restrict on delete restrict; 

alter table "audiousers"
	add constraint "users_FK6" foreign key (
		"userid")
	 references "users" (
		"id") on update restrict on delete restrict; 

alter table "audiousers"
	add constraint "audio_FK4" foreign key (
		"audio")
	 references "audio" (
		"id") on update restrict on delete restrict; 

alter table "audio"
	add constraint "archives_FK1" foreign key (
		"archive")
	 references "archives" (
		"id") on update restrict on delete restrict; 

alter table "audio"
	add constraint "users_FK5" foreign key (
		"creator")
	 references "users" (
		"id") on update restrict on delete restrict; 

alter table "audio"
	add constraint "companies_FK1" foreign key (
		"advert_company")
	 references "companies" (
		"id") on update restrict on delete restrict; 

alter table "audio"
	add constraint "albums_FK1" foreign key (
		"music_album")
	 references "albums" (
		"id") on update restrict on delete restrict; 

alter table "audio"
	add constraint "audiotypes_FK1" foreign key (
		"type")
	 references "audiotypes" (
		"id") on update restrict on delete restrict; 

alter table "audio"
	add constraint "lifespans_FK1" foreign key (
		"lifespan")
	 references "lifespans" (
		"id") on update restrict on delete restrict; 

alter table "dirusers"
	add constraint "dir_FK2" foreign key (
		"directory")
	 references "dir" (
		"id") on update restrict on delete restrict; 

alter table "dirusers"
	add constraint "users_FK4" foreign key (
		"userid")
	 references "users" (
		"id") on update restrict on delete restrict; 

alter table "dirgroups"
	add constraint "dir_FK1" foreign key (
		"directory")
	 references "dir" (
		"id") on update restrict on delete restrict; 

alter table "dirgroups"
	add constraint "groups_FK2" foreign key (
		"groupid")
	 references "groups" (
		"id") on update restrict on delete restrict; 

alter table "groupmembers"
	add constraint "groups_FK1" foreign key (
		"groupid")
	 references "groups" (
		"id") on update restrict on delete restrict; 

alter table "groupmembers"
	add constraint "users_FK3" foreign key (
		"userid")
	 references "users" (
		"id") on update restrict on delete restrict; 

alter table "usersconfigs"
	add constraint "users_FK2" foreign key (
		"userid")
	 references "users" (
		"id") on update restrict on delete restrict; 

alter table "usersconfigs"
	add constraint "configs_FK1" foreign key (
		"configoption")
	 references "configs" (
		"id") on update restrict on delete restrict; 

alter table "useraccess"
	add constraint "users_FK1" foreign key (
		"userid")
	 references "users" (
		"id") on update restrict on delete restrict; 

alter table "useraccess"
	add constraint "privilages_FK1" foreign key (
		"privilage")
	 references "privilages" (
		"id") on update restrict on delete restrict; 

alter table "taskschedule"
	add constraint "tasks_FK1" foreign key (
		"task")
	 references "tasks" (
		"id") on update restrict on delete restrict; 

alter table "sustschedule"
	add constraint "audio_FK3" foreign key (
		"audio")
	 references "audio" (
		"id") on update restrict on delete restrict; 

alter table "sustschedule"
	add constraint "extfeeds_FK1" foreign key (
		"extfeed")
	 references "extfeeds" (
		"id") on update restrict on delete restrict; 

alter table "advertschedule"
	add constraint "audio_FK2" foreign key (
		"advert")
	 references "audio" (
		"id") on update restrict on delete restrict; 

alter table "log"
	add constraint "users_FK9" foreign key (
		"userid")
	 references "users" (
		"id") on update restrict on delete restrict; 

alter table "audiokeywords"
	add constraint "audio_FK1" foreign key (
		"track")
	 references "audio" (
		"id") on update restrict on delete restrict; 

alter table "audiokeywords"
	add constraint "keywords_FK2" foreign key (
		"keyword")
	 references "keywords" (
		"id") on update restrict on delete restrict; 

create view music (title, artist, album) as
select audio.title as title, 
	artists.name as artist, 
	albums.name as album 
from audio, artists, audioartists, albums 
where audioartists.audio = audio.id 
	and audioartists.artist = artists.id 
	and audio.music_album = albums.id
	and audio.type = 0 
order by title;


create view jingles (title, package, type, active) as
select audio.title as title,
    jinglepkgs.name as package,
    jingletypes.description as type,
    jinglepkgs.enabled as active
from audio, jinglepkgs, audiojinglepkgs, jingletypes
where audiojinglepkgs.audio = audio.id
    and audiojinglepkgs.jinglepkg = jinglepkgs.id
    and audiojinglepkgs.jingletype = jingletypes.id
    and audio.type = 1
order by active desc, package, type, title;


-- pgx_grant(PRIVILEGE, TABLES, USER)
--  Grants PRIVILEGE to USER on objects like TABLES%
--  Grants to tables, views and sequences.
--
CREATE FUNCTION pgx_grant(text,text,text) 
returns int4 as '
DECLARE
  priv ALIAS FOR $1;
  patt ALIAS FOR $2;
  user ALIAS FOR $3;
  obj  record;
  num  integer;
BEGIN
  num:=0;
  FOR obj IN SELECT relname FROM pg_class 
  WHERE relname LIKE patt || \'%\' AND relkind in (\'r\',\'v\',\'S\') LOOP
    EXECUTE \'GRANT \' || priv || \' ON \' || obj.relname || \' TO \' || user;
    num := num + 1;
  END LOOP;
  RETURN num;
END;'
language 'plpgsql';



create user digiplay_user;     
pgx_grant("select","%","digiplay_user");


create user digiplay_admin; 
pgx_grant("ALL","%","digiplay_admin");





create rule r_configuration_update 
as on update 
to configuration 
do NOTIFY trig_id1;


create rule r_configuration_insert 
as on insert 
to configuration 
do NOTIFY trig_id1;


create rule r_cartsaudio_update 
as on update 
to cartsaudio 
do NOTIFY trig_id3;


create rule r_cartsaudio_insert
as on insert 
to cartsaudio 
do NOTIFY trig_id3;


create rule r_cartsaudio_delete 
as on delete 
to cartsaudio 
do NOTIFY trig_id3;


create rule r_email_update 
as on update 
to email 
do NOTIFY trig_id2;


create rule r_email_insert 
as on insert 
to email 
do NOTIFY trig_id2;


create rule r_email_delete 
as on delete 
to email 
do NOTIFY trig_id2;



-- This is the end of the Microsoft Visual Studio generated SQL DDL script.
end transaction;

