:%s/"id" INTEGER not null/"id" SERIAL/g
:%s/VARCHAR(10)/VARCHAR/g
:1
i
-- DO NOT EDIT THIS FILE, IT IS AUTOGENERATED!! --

:15
i
create database digiplay;
create user digiplay_user;
\c digiplay
begin transaction;


€ý5Gi€ý=
end transaction;

:wq
